# Generated by Django 3.2.16 on 2023-09-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230926_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(blank=True, to='posts.Follow', verbose_name='Подписки'),
        ),
    ]
